import {
  IconFlame,
  IconCoins,
  IconHeart,
  IconHeartFilled,
  IconLock,
  IconTrendingUp,
  IconTrendingDown,
  IconChevronRight,
  IconChevronLeft,
  IconChevronDown,
  IconCheck,
  IconCircleCheckFilled,
  IconX,
  IconArrowLeft,
  IconSettings,
  IconUserCircle,
  IconHome2,
  IconWallet,
  IconTrophy,
  IconChartLine,
  IconChartCandle,
  IconChartPie,
  IconCoin,
  IconInfoCircle,
  IconStar,
  IconBuildingBank,
  IconPigMoney,
  IconReportAnalytics,
  IconStack2,
  IconShieldCheck,
  IconArrowUpRight,
  IconArrowDownRight,
  IconPlus,
  IconReceipt,
  IconListDetails,
  IconTargetArrow,
  IconSparkles,
  IconRocket,
  IconWorld,
  IconArrowsExchange,
  IconCalendarStats,
  IconScale,
  IconNews,
  IconBriefcase,
  IconShoppingCart,
  IconArrowRight,
} from '@tabler/icons-react';

const ICONS = {
  flame: IconFlame,
  coins: IconCoins,
  coin: IconCoin,
  heart: IconHeart,
  'heart-filled': IconHeartFilled,
  lock: IconLock,
  'trending-up': IconTrendingUp,
  'trending-down': IconTrendingDown,
  'chevron-right': IconChevronRight,
  'chevron-left': IconChevronLeft,
  'chevron-down': IconChevronDown,
  check: IconCheck,
  'circle-check': IconCircleCheckFilled,
  close: IconX,
  back: IconArrowLeft,
  settings: IconSettings,
  user: IconUserCircle,
  home: IconHome2,
  wallet: IconWallet,
  trophy: IconTrophy,
  'chart-line': IconChartLine,
  'chart-candle': IconChartCandle,
  'chart-pie': IconChartPie,
  info: IconInfoCircle,
  star: IconStar,
  'building-bank': IconBuildingBank,
  'piggy-bank': IconPigMoney,
  'report-analytics': IconReportAnalytics,
  'stack-2': IconStack2,
  shield: IconShieldCheck,
  'arrow-up-right': IconArrowUpRight,
  'arrow-down-right': IconArrowDownRight,
  plus: IconPlus,
  receipt: IconReceipt,
  'list-details': IconListDetails,
  target: IconTargetArrow,
  sparkles: IconSparkles,
  rocket: IconRocket,
  world: IconWorld,
  exchange: IconArrowsExchange,
  calendar: IconCalendarStats,
  scale: IconScale,
  news: IconNews,
  briefcase: IconBriefcase,
  'shopping-cart': IconShoppingCart,
  'arrow-right': IconArrowRight,
  'shield-check': IconShieldCheck,
};

export default function Icon({ name, size = 20, color, stroke = 1.9, className }) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp size={size} color={color} stroke={stroke} className={className} />;
}
