/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppLeagueRouteImport } from './routes/_app.league'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSimulateRouteImport } from './routes/_app.simulate'
import { Route as AppLessonsIndexRouteImport } from './routes/_app.lessons.index'
import { Route as AppLessonsLessonIdRouteImport } from './routes/_app.lessons.$lessonId'
import { Route as AppNewsIndexRouteImport } from './routes/_app.news.index'
import { Route as AppNewsArticleIdRouteImport } from './routes/_app.news.$articleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLeagueRoute = AppLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulateRoute = AppSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsIndexRoute = AppLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsLessonIdRoute = AppLessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsArticleIdRoute = AppNewsArticleIdRouteImport.update({
  id: '/news/$articleId',
  path: '/news/$articleId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/league': typeof AppLeagueRoute
  '/profile': typeof AppProfileRoute
  '/simulate': typeof AppSimulateRoute
  '/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/news/$articleId': typeof AppNewsArticleIdRoute
  '/lessons/': typeof AppLessonsIndexRoute
  '/news/': typeof AppNewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/league': typeof AppLeagueRoute
  '/profile': typeof AppProfileRoute
  '/simulate': typeof AppSimulateRoute
  '/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/news/$articleId': typeof AppNewsArticleIdRoute
  '/lessons': typeof AppLessonsIndexRoute
  '/news': typeof AppNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/league': typeof AppLeagueRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/simulate': typeof AppSimulateRoute
  '/_app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/_app/news/$articleId': typeof AppNewsArticleIdRoute
  '/_app/lessons/': typeof AppLessonsIndexRoute
  '/_app/news/': typeof AppNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/league'
    | '/profile'
    | '/simulate'
    | '/lessons/$lessonId'
    | '/news/$articleId'
    | '/lessons/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/league'
    | '/profile'
    | '/simulate'
    | '/lessons/$lessonId'
    | '/news/$articleId'
    | '/lessons'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/_app/league'
    | '/_app/profile'
    | '/_app/simulate'
    | '/_app/lessons/$lessonId'
    | '/_app/news/$articleId'
    | '/_app/lessons/'
    | '/_app/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/league': {
      id: '/_app/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof AppLeagueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulate': {
      id: '/_app/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof AppSimulateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons/': {
      id: '/_app/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AppLessonsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons/$lessonId': {
      id: '/_app/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AppLessonsLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/': {
      id: '/_app/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/$articleId': {
      id: '/_app/news/$articleId'
      path: '/news/$articleId'
      fullPath: '/news/$articleId'
      preLoaderRoute: typeof AppNewsArticleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLeagueRoute: typeof AppLeagueRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSimulateRoute: typeof AppSimulateRoute
  AppLessonsLessonIdRoute: typeof AppLessonsLessonIdRoute
  AppNewsArticleIdRoute: typeof AppNewsArticleIdRoute
  AppLessonsIndexRoute: typeof AppLessonsIndexRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeagueRoute: AppLeagueRoute,
  AppProfileRoute: AppProfileRoute,
  AppSimulateRoute: AppSimulateRoute,
  AppLessonsLessonIdRoute: AppLessonsLessonIdRoute,
  AppNewsArticleIdRoute: AppNewsArticleIdRoute,
  AppLessonsIndexRoute: AppLessonsIndexRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
